name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Build Lambda code
        run: npm run build

      - name: Zip Lambda code
        run: |
          cd dist
          zip -r ../lambda.zip .

      - name: Deploy Lambda function
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.AWS_LAMBDA_NAME }}
          zip_file: lambda.zip
